/* ============================================================================
   Communications Radar v2 mockups — canonical sample dataset.
   Every mockup inlines this object verbatim (standalone HTML, file:// safe).
   Field contract mirrors the live console payload built in
   tool/dashboard.py::_build_mr_rows / _mr_gate_fields.
   ========================================================================== */
const RADAR = {
  meta: {
    user: "Sara",
    dateLabel: "Tuesday 10 June 2026",
    scanTime: "06:40",
    signals: 247,
    sources: 38,
    newToday: 2,
    callReady: 6,
    synthesis: "Three calls worth making before lunch. Reckitt is the one that won't wait — the CEO RNS landed this morning and the corporate-affairs reset clock is already running. Octopus and Monzo close out the morning; both windows are short and both paths in are warm.",
    planOrder: ["reckitt", "monzo", "octopus"]
  },
  leads: [
    {
      id: "reckitt", co: "Reckitt", sector: "Consumer Health",
      type: "Leadership", key: "lead",
      seat: "Corporate Affairs Director",
      win: "~6 weeks", winDays: 42,
      score: 87, tier: "ready", conf: "High",
      ver: "reg", rt: 1, conviction: 84,
      isNew: 1, age: 0,
      fee: "FEE EVENT",
      feeTip: "CEO transitions convert to retained senior searches at the highest rate of any trigger on the desk",
      prop: "Proven agency user", propCls: "pro",
      propWhy: "retained external search for its last two senior comms hires (2023, 2024)",
      qual: { seat: 2, budget: 2, urgency: 1, buyer: 2, total: 7,
        seat_why: "Corporate Affairs Director seat named in two independent reports",
        budget_why: "FTSE-25 with an active leadership-transition budget line",
        urgency_why: "September CEO start gives a six-week decision window, not days",
        buyer_why: "Incoming CEO signs the hire; warm path to the CHRO on file" },
      hook: "New CEO confirmed for September — the corporate-affairs reset usually happens before the role is ever advertised.",
      whyNow: "An incoming CEO typically resets the corporate-affairs function inside the first hundred days, and the senior comms seat is usually the first appointment made — before any role is advertised. This morning's RNS confirms a September start, which puts the real decision window inside the next six weeks.",
      bizCase: "FTSE-25 consumer health group, incoming CEO, no permanent deputy bench. A retained Corporate Affairs Director search at this level carries a £75–90k fee.",
      buyer: "Kris Licht, incoming CEO",
      champion: "via Sarah Cunningham, CHRO — VMA placed her Head of Internal Comms in 2023",
      kill: "Internal promotion of the current deputy, Anna Marsh — she has covered the seat through two previous transitions.",
      opening: "Congratulate on the CEO announcement, then offer the FTSE consumer-health comms-leadership benchmark VMA mapped in April — value first, no ask.",
      opener: "Saw this morning's RNS confirming the September CEO transition — congratulations. When leadership changes at this level, the corporate-affairs brief is usually reset within the first hundred days, well before anything is advertised. We mapped the FTSE consumer-health comms bench in April; happy to share what the strongest available leaders look like before you go to market.",
      anti: [], conflict: 0, q4: null, gateWhy: "",
      stack: [
        { label: "RNS: CEO succession announcement", src: "londonstockexchange.com", age: 0, kind: "Registry" },
        { label: "FT: Reckitt names next chief executive", src: "ft.com", age: 0, kind: "Press" },
        { label: "PRWeek: comms team braced for reset", src: "prweek.com", age: 2, kind: "Trade" }
      ]
    },
    {
      id: "octopus", co: "Octopus Energy", sector: "Energy",
      type: "Funding", key: "fund",
      seat: "Head of External Communications",
      win: "~2 months", winDays: 60,
      score: 81, tier: "ready", conf: "High",
      ver: "multi", rt: 1, conviction: 78,
      isNew: 1, age: 0,
      fee: "FEE EVENT",
      feeTip: "Raises at this scale fund a senior comms build-out and historically convert to external searches",
      prop: "Leans external", propCls: "ext",
      propWhy: "no in-house TA for senior comms; the last three senior hires came through agencies",
      qual: { seat: 2, budget: 2, urgency: 1, buyer: 1, total: 6,
        seat_why: "US expansion announced with no named external-comms owner",
        budget_why: "£600m Series F closed Monday — build-out budget is live",
        urgency_why: "Hire usually lands before the first US market launch",
        buyer_why: "CMO owns the hire; path is warm but one step removed" },
      hook: "£600m Series F closed Monday and a US expansion announced — with no senior external-comms owner named.",
      whyNow: "A raise of this size funds a senior comms build-out, usually within two months — and the US expansion announced alongside it has no named external-communications lead. The hire that lands the expansion story tends to be made before the first US market launch.",
      bizCase: "Britain's largest energy supplier going into a US launch with an empty external-comms seat. A search at this level carries a £55–70k fee.",
      buyer: "Rebecca Dibb-Simkin, CMO",
      champion: "warm — VMA was shortlisted for their 2024 brand-comms brief and the door was left open",
      kill: "They promote from the energy-services comms team rather than hire externally — possible, but it has not been their pattern at this level.",
      opening: "Reference the raise and the US launch in one breath, then ask who owns the expansion story externally — the silence in their own announcement is the opening.",
      opener: "Congratulations on Monday's raise — £600m and a US launch in the same announcement is quite a story to land. We noticed no external-comms owner was named for the expansion. We run the senior comms desk for UK energy and have three leaders who have taken a British brand into the US market; worth a short call before you scope the role?",
      anti: [], conflict: 0, q4: null, gateWhy: "",
      stack: [
        { label: "TechCrunch: Octopus closes £600m Series F", src: "techcrunch.com", age: 0, kind: "Press" },
        { label: "Sky News: US expansion to follow raise", src: "news.sky.com", age: 0, kind: "Press" }
      ]
    },
    {
      id: "monzo", co: "Monzo", sector: "Fintech",
      type: "Comms exit", key: "lead",
      seat: "Director of Communications",
      win: "~4 weeks", winDays: 28,
      score: 76, tier: "ready", conf: "High",
      ver: "multi", rt: 1, conviction: 71,
      isNew: 0, age: 2,
      fee: "FEE EVENT",
      feeTip: "A vacated senior seat is the most direct fee event on the desk — the replacement search opens fast",
      prop: "Leans external", propCls: "ext",
      propWhy: "external-hiring signals on the last two senior people moves; no executive-search function in-house",
      qual: { seat: 2, budget: 1, urgency: 2, buyer: 1, total: 6,
        seat_why: "The exact seat has just been vacated — no inference needed",
        budget_why: "Backfill budget assumed but not yet evidenced",
        urgency_why: "Results season lands in July with the seat empty in four weeks",
        buyer_why: "CEO signs senior comms hires personally; path runs through VP People" },
      hook: "Comms director announced her exit to Revolut on Friday — the seat is empty in four weeks, with results season ahead.",
      whyNow: "The senior comms seat has just been vacated, so the replacement search tends to open within four weeks — and Monzo walks into results season in July without a comms director unless it moves first. Exits to a direct rival also add pressure to re-stake the narrative quickly.",
      bizCase: "UK's biggest digital bank entering results season with the comms chair empty. A Director-level search carries a £50–65k fee, and speed is the differentiator here.",
      buyer: "TS Anil, CEO — signs senior comms hires personally",
      champion: "via Hannah Bertolini, VP People — responded warmly to VMA's candidate note in March",
      kill: "An internal step-up by the policy-comms lead. She lacks consumer-press experience, so it would be a stretch — but boards under time pressure do stretch.",
      opening: "Don't mention Revolut. Lead with the July results date and offer two names who could hold the chair from week one — speed is the whole pitch.",
      opener: "With results season landing in July, four weeks is a tight window to have the comms chair empty. We hold a live shortlist of consumer-fintech comms directors — two could be in the seat within notice. Worth fifteen minutes this week before the gap starts costing coverage?",
      anti: [], conflict: 0, q4: null, gateWhy: "",
      stack: [
        { label: "Financial News: Monzo comms chief departs for Revolut", src: "fnlondon.com", age: 2, kind: "Press" },
        { label: "LinkedIn: departure post by the outgoing director", src: "linkedin.com", age: 2, kind: "Social" }
      ]
    },
    {
      id: "severn", co: "Severn Trent", sector: "Water Utilities",
      type: "Regulator action", key: "warn",
      seat: "Head of Corporate Communications",
      win: "~6 weeks", winDays: 42,
      score: 72, tier: "ready", conf: "High",
      ver: "reg", rt: 1, conviction: 69,
      isNew: 0, age: 4,
      fee: "FEE EVENT",
      feeTip: "Enforcement action raises the reputation-comms bar; a senior hire usually follows within the response window",
      prop: "Proven agency user", propCls: "pro",
      propWhy: "history of agency use on senior comms and regulatory-affairs hires on file",
      qual: { seat: 2, budget: 1, urgency: 2, buyer: 2, total: 7,
        seat_why: "Head of Corporate Communications named as vacant in trade coverage",
        budget_why: "Regulatory-response budget likely but not yet evidenced",
        urgency_why: "Ofwat response deadline fixed at eight weeks from notice",
        buyer_why: "Corporate Affairs Director is the named owner of the response" },
      hook: "Ofwat enforcement notice published Thursday — the response needs a senior comms owner and the current seat is vacant.",
      whyNow: "Regulatory enforcement raises the reputation-comms bar overnight, and the formal response window is fixed: eight weeks from notice. The Head of Corporate Communications seat is vacant at exactly the moment the company needs a senior owner for the Ofwat narrative.",
      bizCase: "FTSE-100 utility under live enforcement with a vacant comms seat and a fixed deadline. Crisis-adjacent searches close fast and at full fee — £45–60k here.",
      buyer: "James Bowling, Corporate Affairs Director",
      champion: "cold but receptive — opened both VMA sector notes sent this year",
      kill: "They hand the response to their retained agency instead of hiring — mitigated by the seat itself being structurally vacant.",
      opening: "Lead with the eight-week response window and the vacant seat in the same sentence; offer interim-to-permanent options to de-risk the deadline.",
      opener: "With the Ofwat notice setting an eight-week response clock and the corporate-comms seat currently open, you're running the response a person short. We can put senior water-sector comms leaders in front of you this week — including interim-to-permanent options if the deadline is the priority. Worth a short call?",
      anti: [], conflict: 0, q4: null, gateWhy: "",
      stack: [
        { label: "Ofwat: enforcement notice and penalty", src: "ofwat.gov.uk", age: 5, kind: "Registry" },
        { label: "BBC: Severn Trent faces enforcement action", src: "bbc.co.uk", age: 5, kind: "Press" },
        { label: "Utility Week: comms seat vacant amid probe", src: "utilityweek.co.uk", age: 4, kind: "Trade" }
      ]
    },
    {
      id: "haleon", co: "Haleon", sector: "Consumer Health",
      type: "M&A", key: "mna",
      seat: "Head of Internal Communications",
      win: "~3 months", winDays: 90,
      score: 70, tier: "ready", conf: "Medium",
      ver: "multi", rt: 0, conviction: null,
      isNew: 0, age: 6,
      fee: "FEE EVENT",
      feeTip: "Post-deal integration needs senior internal-comms leadership to land the change",
      prop: "Unknown", propCls: "unk",
      propWhy: "no fee-propensity evidence yet — score carries the neutral default",
      qual: { seat: 2, budget: 1, urgency: 1, buyer: 2, total: 6,
        seat_why: "Integration comms lead named as a gap in deal coverage",
        budget_why: "Deal integration budget exists; comms line not yet evidenced",
        urgency_why: "Completion expected Q3 — window is real but not immediate",
        buyer_why: "Chief People Officer named as integration sponsor" },
      hook: "£1.2bn brand-portfolio divestiture confirmed — 2,000 staff transfer and nobody named to land the change internally.",
      whyNow: "Post-deal integration needs senior internal-comms leadership in place before completion, and this divestiture moves roughly two thousand people between owners. Deal coverage names an integration sponsor but no comms owner — the hire usually follows within a quarter.",
      bizCase: "FTSE-30 consumer health group mid-divestiture with a named people-integration sponsor and no comms lead. Internal-comms leadership searches here run £40–55k.",
      buyer: "Tamara Rogers, Chief People Officer (integration sponsor)",
      champion: "no warm path yet — strongest route is the sector note then a direct approach",
      kill: "The acquirer takes integration comms in-house on completion, which would close the seat on Haleon's side.",
      opening: "Frame it around the people transfer, not the deal: two thousand colleagues hearing about their future second-hand is the risk a senior IC hire removes.",
      opener: "With the divestiture confirmed and around two thousand colleagues transferring, the internal story is now the deal's biggest people risk — and coverage so far names an integration sponsor but no comms owner. We specialise in exactly this seat; can I share three integration-comms leaders who have landed a carve-out before?",
      anti: [], conflict: 0, q4: null, gateWhy: "",
      stack: [
        { label: "Reuters: Haleon confirms portfolio divestiture", src: "reuters.com", age: 6, kind: "Press" },
        { label: "PRWeek: integration comms gap flagged", src: "prweek.com", age: 4, kind: "Trade" }
      ]
    },
    {
      id: "diageo", co: "Diageo", sector: "Beverages",
      type: "Restructure", key: "restr",
      seat: "Internal Communications Lead",
      win: "~2 months", winDays: 60,
      score: 68, tier: "ready", conf: "Medium",
      ver: "multi", rt: 0, conviction: null,
      isNew: 0, age: 8,
      fee: null, feeTip: "",
      prop: "Proven agency user", propCls: "pro",
      propWhy: "used external search for both senior comms hires made under the current CMO",
      qual: { seat: 1, budget: 2, urgency: 1, buyer: 1, total: 5,
        seat_why: "Seat inferred from the restructure scope, not yet named",
        budget_why: "FYE 30 June — unspent budget converts to mandates in the next 20 days",
        urgency_why: "Restructure announced; comms implications still forming",
        buyer_why: "Likely the Comms VP, unconfirmed" },
      hook: "Americas restructure announced and the financial year closes 30 June — unspent budget meets a live reorganisation.",
      whyNow: "A restructure reshapes the comms function, and Diageo's year-end on 30 June gives hiring managers twenty days to commit budget they otherwise lose. That combination — live reorganisation plus budget-flush window — is when retained briefs get signed.",
      bizCase: "FTSE-15 drinks group reorganising its biggest region with year-end twenty days out. The budget-flush window is the lever; the restructure is the reason.",
      buyer: "Likely the VP Communications — to be confirmed on the first call",
      champion: "VMA placed two comms managers here in 2022; both still in seat and contactable",
      kill: "The restructure lands as cost-cutting rather than reshaping — in that world comms headcount shrinks instead of churns.",
      opening: "Year-end first, restructure second: budget committed before 30 June survives; budget that isn't, doesn't. Offer to scope the brief this week.",
      opener: "With the Americas restructure in motion and your year-end on 30 June, there's a short window where this year's budget can still carry a senior comms brief. We placed two of your comms managers in 2022 and know the function well — worth scoping the internal-comms lead now so the budget decision is yours rather than the calendar's?",
      anti: [], conflict: 0,
      q4: "Q4 · FYE 30 Jun (20d)", gateWhy: "",
      stack: [
        { label: "WSJ: Diageo restructures Americas business", src: "wsj.com", age: 8, kind: "Press" },
        { label: "The Grocer: comms implications of the reorg", src: "thegrocer.co.uk", age: 7, kind: "Trade" }
      ]
    },
    {
      id: "deliveroo", co: "Deliveroo", sector: "Consumer Tech",
      type: "Job-ad cluster", key: "people",
      seat: "Head of Communications",
      win: "~2 months", winDays: 60,
      score: 58, tier: "dev", conf: "",
      ver: "single", rt: 0, conviction: null,
      isNew: 0, age: 3,
      fee: null, feeTip: "",
      prop: "Unknown", propCls: "unk",
      propWhy: "no fee-propensity evidence yet",
      qual: { seat: 1, budget: 1, urgency: 1, buyer: 0, total: 3,
        seat_why: "Senior seat inferred from the mid-level cluster, not named",
        budget_why: "Three live mid-level salaries imply budget, not proof of it",
        urgency_why: "Cluster is growing but no forcing date",
        buyer_why: "No buyer visible yet" },
      hook: "Three mid-level comms roles posted in a fortnight with no senior owner above them — the senior mandate usually follows.",
      whyNow: "Mid-level comms hiring is already underway with no senior owner visible above it. When a function staffs from the middle out, the senior mandate tends to follow within a quarter — the cluster is the smoke, not yet the fire.",
      bizCase: "", buyer: "", champion: "",
      kill: "", opening: "", opener: "",
      anti: [], conflict: 0, q4: null,
      gateWhy: "Mid-level cluster verified, but the senior-seat inference rests on one evidence family · recheck in 4d · run /investigate",
      stack: [
        { label: "LinkedIn Jobs: 3 comms roles, posted 9–14 days", src: "linkedin.com", age: 3, kind: "Jobs" }
      ]
    },
    {
      id: "astrazeneca", co: "AstraZeneca", sector: "Pharma",
      type: "Chair change", key: "lead",
      seat: "Corporate Affairs Director",
      win: "~3 months", winDays: 90,
      score: 54, tier: "dev", conf: "",
      ver: "reg", rt: 0, conviction: null,
      isNew: 0, age: 5,
      fee: null, feeTip: "",
      prop: "Unknown", propCls: "unk",
      propWhy: "no fee-propensity evidence yet",
      qual: { seat: 0, budget: 1, urgency: 1, buyer: 1, total: 3,
        seat_why: "No comms-function signal yet — the trigger is board-level only",
        budget_why: "Budget capacity assumed at this scale",
        urgency_why: "Chair transitions reset slowly; months not weeks",
        buyer_why: "Would be the incoming chair's office; not yet formed" },
      hook: "New chair announced via RNS — board-level resets reach the comms function more slowly, but they do reach it.",
      whyNow: "A new chair usually reviews board and governance communications within two quarters. The trigger is registry-attested but board-level only — there is no comms-function movement yet, which is what the recheck is waiting for.",
      bizCase: "", buyer: "", champion: "",
      kill: "", opening: "", opener: "",
      anti: [], conflict: 0, q4: null,
      gateWhy: "Board change is registry-attested, but no comms-function signal yet · recheck in 7d",
      stack: [
        { label: "RNS: chair succession announcement", src: "londonstockexchange.com", age: 5, kind: "Registry" }
      ]
    },
    {
      id: "asos", co: "ASOS", sector: "Retail",
      type: "Leadership tenure", key: "people",
      seat: "Director of Communications",
      win: "horizon", winDays: 180,
      score: 38, tier: "early", conf: "",
      ver: "single", rt: 0, conviction: null,
      isNew: 0, age: 11,
      fee: null, feeTip: "",
      prop: "Unknown", propCls: "unk", propWhy: "no fee-propensity evidence yet",
      qual: { seat: 0, budget: 0, urgency: 0, buyer: 0, total: 0,
        seat_why: "No vacancy — watch-grade only",
        budget_why: "No budget signal",
        urgency_why: "No forcing event",
        buyer_why: "No buyer in play" },
      hook: "Comms director enters year seven in the seat — statistically a flight risk, nothing more yet.",
      whyNow: "A long-tenured comms leader is a flight risk worth tracking, not calling. The play is relationship groundwork: be the first call when movement comes, and have a backfill brief ready before anyone else knows there is one.",
      bizCase: "", buyer: "", champion: "",
      kill: "", opening: "", opener: "",
      anti: [], conflict: 0, q4: null,
      gateWhy: "Watch-grade: tenure flag only, no movement signal · keep on the radar",
      stack: [
        { label: "LinkedIn: tenure profile analysis", src: "linkedin.com", age: 11, kind: "Social" }
      ]
    },
    {
      id: "boohoo", co: "Boohoo Group", sector: "Retail",
      type: "Profit warning", key: "warn",
      seat: "Head of Corporate Communications",
      win: "~6 weeks", winDays: 42,
      score: 61, tier: "blocked", conf: "",
      ver: "reg", rt: 0, conviction: null,
      isNew: 0, age: 7,
      fee: null, feeTip: "",
      prop: "Unknown", propCls: "unk", propWhy: "",
      qual: { seat: 2, budget: 1, urgency: 2, buyer: 1, total: 6,
        seat_why: "IR/comms reset named in coverage",
        budget_why: "Budget under pressure post-warning",
        urgency_why: "Warning forces a narrative reset now",
        buyer_why: "CFO office owns the response" },
      hook: "Profit warning would normally open the IR-comms seat — but a competing recruiter already holds the leadership review.",
      whyNow: "A profit warning drives an investor-relations and corporate-comms reset, and this one is registry-attested. It is blocked for one reason only: Russell Reynolds is retained on the wider leadership review, so a call now walks into a competitor's mandate.",
      bizCase: "", buyer: "", champion: "",
      kill: "", opening: "", opener: "",
      anti: ["competing recruiter retained"], conflict: 1, q4: null,
      gateWhy: "Russell Reynolds retained for the wider leadership review — do not call",
      stack: [
        { label: "RNS: trading statement and profit warning", src: "londonstockexchange.com", age: 7, kind: "Registry" },
        { label: "Retail Week: leadership review under way", src: "retail-week.com", age: 6, kind: "Trade" }
      ]
    }
  ]
};
